# Generated by Django 3.1.7 on 2021-06-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0003_post_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='thumbnil',
        ),
    ]
