# Generated by Django 3.1.7 on 2021-06-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0004_auto_20210602_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='post',
        ),
    ]
