# Generated by Django 3.1.7 on 2021-06-02 13:35

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0005_auto_20210602_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vid_url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
